# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-21 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_data.Organization'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_clearance',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
