# Generated by Django 2.1.4 on 2019-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='hardware_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='last_license_check',
            field=models.DateField(null=True),
        ),
    ]
