# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
