# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0002_auto_20180721_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, default='', max_length=32)),
                ('email_post', models.IntegerField(null=True)),
                ('email_user', models.CharField(blank=True, default='', max_length=32)),
                ('email_password', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
