# Generated by Django 2.1.1 on 2018-12-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0002_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
