# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0003_globalconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalconfig',
            old_name='email_post',
            new_name='email_port',
        ),
    ]
