# Generated by Django 2.2 on 2019-04-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0004_auto_20190423_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
    ]
