# Generated by Django 2.1.8 on 2019-04-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0005_globalconfig_is_configured'),
        ('common_data', '0005_auto_20190426_1558'),
    ]

    operations = [
    ]
