# Generated by Django 2.1.4 on 2019-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0006_auto_20190201_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='application_version',
            field=models.CharField(blank=True, default='0.0.1', max_length=16),
        ),
    ]
