# Generated by Django 2.1.8 on 2019-05-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0007_globalconfig_logo_aspect_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='logo_aspect_ratio',
            field=models.PositiveSmallIntegerField(choices=[(0, '3:2 (Medium rectangle)'), (1, '1:1 (Square)'), (2, '4:3 (Narrower Rectangle)'), (3, ':16:9 (Wide Rectangle)')], default=0),
        ),
    ]
