# Generated by Django 2.1.4 on 2019-03-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0007_globalconfig_application_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='tax_clearance',
            new_name='bpn_number',
        ),
    ]
