# Generated by Django 2.1.4 on 2019-03-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0008_auto_20190329_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='bpn_number',
            new_name='bp_number',
        ),
    ]
