# Generated by Django 2.1.8 on 2019-06-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0009_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfig',
            name='backup_location',
        ),
        migrations.RemoveField(
            model_name='globalconfig',
            name='backup_location_type',
        ),
        migrations.RemoveField(
            model_name='globalconfig',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='globalconfig',
            name='email_password',
        ),
        migrations.RemoveField(
            model_name='globalconfig',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='globalconfig',
            name='email_user',
        ),
    ]
