# Generated by Django 2.1.1 on 2018-11-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Annual Leave'), (2, 'Sick Leave'), (3, 'Study Leave'), (4, 'Maternity Leave'), (5, 'Parental Leave'), (5, 'Bereavement Leave')])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Authorized'), (2, 'Declined')])),
                ('authorized_by', models.ForeignKey(on_delete=None, related_name='authority', to='employees.Employee')),
                ('employee', models.ForeignKey(on_delete=None, related_name='employee', to='employees.Employee')),
            ],
        ),
    ]
