# Generated by Django 2.1.1 on 2018-09-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygrade',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='employees.CommissionRule'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='payroll_tax',
            field=models.ForeignKey(on_delete=None, to='employees.PayrollTax'),
        ),
    ]
