# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
