# Generated by Django 2.1.1 on 2018-11-15 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paygrade',
            name='lunch_duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AddField(
            model_name='paygrade',
            name='subtract_lunch_time_from_working_hours',
            field=models.BooleanField(default=False),
        ),
    ]
