# Generated by Django 2.1.4 on 2019-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paygrade',
            old_name='monthly_salary',
            new_name='salary',
        ),
        migrations.AddField(
            model_name='paygrade',
            name='pay_frequency',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Weekly'), (1, 'Bi-Monthly'), (2, 'Monthly')], default=2),
        ),
    ]
