# Generated by Django 2.1.1 on 2018-11-15 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20181115_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygrade',
            name='lunch_duration',
            field=models.DurationField(choices=[(datetime.timedelta(0, 900), '15 min.'), (datetime.timedelta(0, 1800), '30 min.'), (datetime.timedelta(0, 2700), '45 min.'), (datetime.timedelta(0, 3600), '1 hr.')], default=datetime.timedelta(0, 3600)),
        ),
    ]
