# Generated by Django 2.1.1 on 2018-10-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20181025_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetimesheet',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
