# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_allowance_taxable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('paid_by', models.IntegerField(choices=[(0, 'Employees'), (1, 'Employer')])),
            ],
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_boundary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('upper_boundary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deduction', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
