# Generated by Django 2.1.1 on 2018-11-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Authorized'), (2, 'Declined')], default=0),
        ),
    ]
