# Generated by Django 2.1.1 on 2018-10-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20181026_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pin',
            field=models.PositiveSmallIntegerField(default=277),
        ),
        migrations.AlterField(
            model_name='attendanceline',
            name='lunch_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceline',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceline',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetimesheet',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=None, related_name='recorder', to='employees.Employee'),
        ),
    ]
