# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_payrolltax_taxbracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxbracket',
            name='payroll_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.PayrollTax'),
        ),
    ]
