# Generated by Django 2.1.1 on 2018-11-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20181119_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=None, related_name='authority', to='employees.Employee'),
        ),
    ]
