# Generated by Django 2.1.1 on 2018-10-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20181026_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='uses_timesheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pin',
            field=models.PositiveSmallIntegerField(default=8449),
        ),
    ]
