# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_taxbracket_payroll_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='paygrade',
            name='payroll_taxes',
            field=models.ManyToManyField(blank=True, to='employees.PayrollTax'),
        ),
    ]
