# Generated by Django 2.1.1 on 2018-11-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20181119_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
