# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_paygrade_payroll_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_date_one', models.PositiveSmallIntegerField()),
                ('payroll_date_two', models.PositiveSmallIntegerField()),
                ('payroll_date_three', models.PositiveSmallIntegerField()),
                ('payroll_date_four', models.PositiveSmallIntegerField()),
                ('payroll_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('bi-monthly', 'Bi-monthly'), ('monthly', 'Monthly')], max_length=12)),
                ('require_verification_before_posting_payslips', models.BooleanField(default=True)),
                ('automate_payroll_for', models.ManyToManyField(to='employees.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
