# Generated by Django 2.1.1 on 2018-11-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20181115_1804'),
        ('employees', '0005_leave_notes'),
    ]

    operations = [
    ]
