# Generated by Django 2.1.1 on 2018-10-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20181026_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pin',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uses_timesheet',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
