# Generated by Django 2.1.1 on 2018-11-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_merge_20181119_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_leave_day_increment',
            field=models.DateField(null=True),
        ),
    ]
