# Generated by Django 2.1.1 on 2018-10-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20181026_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeessettings',
            name='last_payroll_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeessettings',
            name='payroll_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='payroll_officer', to='employees.Employee'),
        ),
    ]
