# Generated by Django 2.1.8 on 2019-05-08 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20190506_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pay_grade',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.PayGrade'),
        ),
    ]
