# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeessettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeessettings',
            name='salary_follows_profits',
            field=models.BooleanField(default=True),
        ),
    ]
