# Generated by Django 2.1.1 on 2018-10-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20181029_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeessettings',
            name='payroll_counter',
            field=models.IntegerField(default=0),
        ),
    ]
