# Generated by Django 2.1.1 on 2018-11-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_last_leave_day_increment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='recorded',
            field=models.BooleanField(default=False),
        ),
    ]
