# Generated by Django 2.1.8 on 2019-05-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20190508_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pay_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.PayGrade'),
        ),
    ]
