# Generated by Django 2.1.1 on 2018-10-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeessettings_payroll_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeessettings',
            name='automate_payroll_for',
            field=models.ManyToManyField(blank=True, to='employees.Employee'),
        ),
    ]
