# Generated by Django 2.1.8 on 2019-07-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20190513_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction',
            old_name='amount',
            new_name='fixed_amount',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='method',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='trigger',
        ),
        migrations.AddField(
            model_name='deduction',
            name='basic_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deduction',
            name='benefits',
            field=models.ManyToManyField(to='employees.Allowance'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='commisssion',
            field=models.ManyToManyField(to='employees.CommissionRule'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='deduction_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Fixed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deduction',
            name='employer_contribution',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deduction',
            name='hourly_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deduction',
            name='overtime_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deduction',
            name='payroll_taxes',
            field=models.ManyToManyField(to='employees.PayrollTax'),
        ),
    ]
