# Generated by Django 2.1.1 on 2018-12-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_leave_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayGradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('serialized_data', models.TextField()),
                ('instance', models.ForeignKey(on_delete=None, to='employees.PayGrade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
