# Generated by Django 2.1.1 on 2018-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_paygradehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='paygrade_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
