# Generated by Django 2.1.8 on 2019-07-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20190702_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction',
            old_name='commisssion',
            new_name='commission',
        ),
    ]
