# Generated by Django 2.1.1 on 2018-12-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_payslip_pay_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='pay_grade_version',
            field=models.PositiveSmallIntegerField(default=0),
        )
    ]
