# Generated by Django 2.1.8 on 2019-07-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20190702_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='tax_deductable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payrolltax',
            name='paid_by',
            field=models.IntegerField(choices=[(0, 'Employees'), (1, 'Employer'), (2, 'Both')]),
        ),
    ]
