# Generated by Django 2.1.1 on 2018-12-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_accountingsettings_currency_exchange_table'),
        ('employees', '0010_payslip_paygrade_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='account_paid_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='accounting.Account'),
        ),
    ]
