# Generated by Django 2.1.1 on 2018-12-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20181218_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygrade',
            name='subtract_lunch_time_from_working_hours',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
