# Generated by Django 2.1.8 on 2019-07-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20190705_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
