# Generated by Django 2.1.8 on 2019-08-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20190812_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='paygrade',
            name='maximum_leave_days',
            field=models.FloatField(default=60.0),
        ),
    ]
