# Generated by Django 2.1.4 on 2019-01-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_auto_20181224_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceline',
            name='timesheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.EmployeeTimeSheet'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='account_paid_into',
            field=models.ForeignKey(default=5008, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Account'),
        ),
        migrations.AlterField(
            model_name='employeessettings',
            name='payroll_account',
            field=models.ForeignKey(default=1000, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Account'),
        ),
        migrations.AlterField(
            model_name='employeessettings',
            name='payroll_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'payrollofficer__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_officer', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='employeetimesheet',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='employeetimesheet',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorder', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='authorized_by',
            field=models.ForeignKey(limit_choices_to={'payroll_officer__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='paygrade',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.CommissionRule'),
        ),
        migrations.AlterField(
            model_name='payrollofficer',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.JournalEntry'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pay_grade',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.PayGrade'),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='payroll_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.PayrollTax'),
        ),
    ]
