# Generated by Django 2.1 on 2019-09-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_paygrade_maximum_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeessettings',
            name='business_social_security_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
