# Generated by Django 2.1 on 2019-09-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employeessettings_business_social_security_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('job_position', models.CharField(blank=True, max_length=255)),
                ('end_of_probation', models.DateField()),
                ('termination_date', models.DateField()),
                ('nature_of_employment', models.CharField(choices=[('A', 'Arduous'), ('N', 'Normal')], default='N', max_length=1)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason_for_termination', models.CharField(choices=[('R', 'Retirement'), ('C', 'Casual Employee'), ('D', 'Death'), ('O', 'Other')], default='R', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Contract'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Termination'),
        ),
    ]
