# Generated by Django 2.1.4 on 2019-03-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_auto_20190112_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.PositiveSmallIntegerField()),
                ('employees', models.ManyToManyField(to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
