# Generated by Django 2.1 on 2019-09-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_auto_20190910_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='termination',
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='termination',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Contract'),
        ),
    ]
