# Generated by Django 2.1.4 on 2019-03-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_payrolldate_payrollschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('employees', models.ManyToManyField(related_name='employees', to='employees.Employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='employees.Employee')),
                ('parent_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Department')),
            ],
        ),

        migrations.RemoveField(
            model_name='employeessettings',
            name='automate_payroll_for',
        ),
        migrations.RemoveField(
            model_name='employeessettings',
            name='payroll_cycle',
        ),
        migrations.RemoveField(
            model_name='employeessettings',
            name='payroll_date_four',
        ),
        migrations.RemoveField(
            model_name='employeessettings',
            name='payroll_date_one',
        ),
        migrations.RemoveField(
            model_name='employeessettings',
            name='payroll_date_three',
        ),
        migrations.RemoveField(
            model_name='employeessettings',
            name='payroll_date_two',
        ),
        migrations.AddField(
            model_name='payrolldate',
            name='pay_grades',
            field=models.ManyToManyField(to='employees.PayGrade'),
        ),
        
        migrations.AddField(
            model_name='payrolldate',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.PayrollSchedule'),
        ),
        migrations.AlterField(
            model_name='payrolldate',
            name='date',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28)]),
        ),
        migrations.AddField(
            model_name='payrolldate',
            name='departments',
            field=models.ManyToManyField(to='employees.Department'),
        ),
    ]
