# Generated by Django 2.1 on 2019-09-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_auto_20190912_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termination',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Contract'),
        ),
    ]
