# Generated by Django 2.1 on 2019-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_remove_employee_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxbracket',
            name='deduction',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='lower_boundary',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='upper_boundary',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
