# Generated by Django 2.1 on 2019-09-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20190923_1226'),
        ('employees', '0021_auto_20190923_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='liability_account',
            field=models.ForeignKey(default=2010, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='liability_account', to='accounting.Account'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='account_paid_into',
            field=models.ForeignKey(default=5008, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='expense_account', to='accounting.Account'),
        ),
    ]
