# Generated by Django 2.1.8 on 2019-07-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicessettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderrequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
