# Generated by Django 2.1.4 on 2019-01-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20181101_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablesrequisition',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_authorized_by', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='consumablesrequisition',
            name='released_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_released_by', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='consumablesrequisition',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_requested_by', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='consumablesrequisitionline',
            name='consumable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Consumable'),
        ),
        migrations.AlterField(
            model_name='consumablesrequisitionline',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='equipmentrequisitionline',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Equipment'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ServiceCategory'),
        ),
        migrations.AlterField(
            model_name='serviceperson',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='serviceteam',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_team_manager', to='services.ServicePerson'),
        ),
        migrations.AlterField(
            model_name='serviceworkorder',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ServiceTeam'),
        ),
    ]
