# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-19 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180819_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceProcedure'),
        ),
        migrations.AddField(
            model_name='serviceteam',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServicesManager'),
        ),
        migrations.AddField(
            model_name='serviceteam',
            name='members',
            field=models.ManyToManyField(to='services.ServicesPerson'),
        ),
        migrations.AddField(
            model_name='serviceworkorder',
            name='service_people',
            field=models.ManyToManyField(blank=True, to='services.ServicesPerson'),
        ),
        migrations.AddField(
            model_name='task',
            name='procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceProcedure'),
            preserve_default=False,
        ),
    ]
