# Generated by Django 2.1.4 on 2019-01-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_auto_20190112_2256'),
        ('services', '0003_auto_20190104_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequisition',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='equipmentrequisition',
            name='returned_date',
            field=models.DateField(null=True),
        ),
    ]
