# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-19 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20180819_0342'),
        ('services', '0003_auto_20180819_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablesrequisition',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.WareHouse'),
        ),
        migrations.AddField(
            model_name='equipmentrequisition',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.WareHouse'),
        ),
    ]
