# Generated by Django 2.1.4 on 2019-01-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_auto_20190129_1933'),
        ('invoicing', '0012_salesinvoice_shipping_expenses'),
        ('services', '0004_auto_20190115_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Expense')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.PositiveSmallIntegerField(choices=[(0, 'Service Invoice'), (1, 'Combined Invoice')])),
                ('status', models.CharField(choices=[('request', 'Requested'), ('in-progress', 'In Progress'), ('completed', 'Completed')], max_length=16)),
                ('combined_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.CombinedInvoice')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.ServiceInvoice')),
            ],
        ),
        migrations.AddField(
            model_name='serviceworkorder',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorderexpense',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ServiceWorkOrder'),
        ),
        migrations.AddField(
            model_name='serviceworkorder',
            name='works_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.WorkOrderRequest'),
        ),
    ]
