# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('services', '0004_auto_20180819_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False)),
                ('can_authorize_equipment_requisitions', models.BooleanField(default=False)),
                ('can_authorize_consumables_requisitions', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicesmanager',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='servicesperson',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='serviceteam',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='serviceteam',
            name='members',
        ),
        migrations.RemoveField(
            model_name='serviceworkorder',
            name='service_people',
        ),
        migrations.DeleteModel(
            name='ServicesManager',
        ),
        migrations.DeleteModel(
            name='ServicesPerson',
        ),
    ]
