# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180824_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceteam',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_team_manager', to='services.ServicePerson'),
        ),
        migrations.AddField(
            model_name='serviceteam',
            name='members',
            field=models.ManyToManyField(related_name='service_team_members', to='services.ServicePerson'),
        ),
        migrations.AddField(
            model_name='serviceworkorder',
            name='service_people',
            field=models.ManyToManyField(blank=True, to='services.ServicePerson'),
        ),
    ]
