# Generated by Django 2.1.4 on 2019-01-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190131_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderrequest',
            name='combined_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.CombinedInvoice'),
        ),
        migrations.AlterField(
            model_name='workorderrequest',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.ServiceInvoice'),
        ),
    ]
