# Generated by Django 2.1.4 on 2019-01-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190131_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorderrequest',
            old_name='invoice',
            new_name='service_invoice',
        ),
    ]
