# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20180824_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceworkorder',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='serviceworkorder',
            name='status',
            field=models.CharField(blank=True, choices=[('requested', 'Requested'), ('progress', 'In progress'), ('completed', 'Completed'), ('authorized', 'Authorized'), ('declined', 'Declined')], max_length=16),
        ),
    ]
