# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20180824_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceworkorder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
