# Generated by Django 2.1.4 on 2019-01-31 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190131_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablesrequisition',
            name='work_order',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('status', 'progress'), ('status', 'requested'), _connector='OR')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ServiceWorkOrder'),
        ),
        migrations.AddField(
            model_name='equipmentrequisition',
            name='work_order',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('status', 'progress'), ('status', 'requested'), _connector='OR')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ServiceWorkOrder'),
        ),
    ]
