# Generated by Django 2.1.4 on 2019-01-31 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20190131_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderrequest',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
    ]
