# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 05:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_serviceworkorder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablesrequisitionline',
            name='requisition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.ConsumablesRequisition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentrequisitionline',
            name='requisition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.EquipmentRequisition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceworkorder',
            name='actual_duration',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(0), '00:00'), (datetime.timedelta(0, 1800), '00:30'), (datetime.timedelta(0, 3600), '01:00'), (datetime.timedelta(0, 5400), '01:30'), (datetime.timedelta(0, 7200), '02:00'), (datetime.timedelta(0, 9000), '02:30'), (datetime.timedelta(0, 10800), '03:00'), (datetime.timedelta(0, 12600), '03:30'), (datetime.timedelta(0, 14400), '04:00'), (datetime.timedelta(0, 16200), '04:30'), (datetime.timedelta(0, 18000), '05:00'), (datetime.timedelta(0, 19800), '05:30'), (datetime.timedelta(0, 21600), '06:00'), (datetime.timedelta(0, 23400), '06:30'), (datetime.timedelta(0, 25200), '07:00'), (datetime.timedelta(0, 27000), '07:30')], null=True),
        ),
        migrations.AlterField(
            model_name='serviceworkorder',
            name='expected_duration',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(0), '00:00'), (datetime.timedelta(0, 1800), '00:30'), (datetime.timedelta(0, 3600), '01:00'), (datetime.timedelta(0, 5400), '01:30'), (datetime.timedelta(0, 7200), '02:00'), (datetime.timedelta(0, 9000), '02:30'), (datetime.timedelta(0, 10800), '03:00'), (datetime.timedelta(0, 12600), '03:30'), (datetime.timedelta(0, 14400), '04:00'), (datetime.timedelta(0, 16200), '04:30'), (datetime.timedelta(0, 18000), '05:00'), (datetime.timedelta(0, 19800), '05:30'), (datetime.timedelta(0, 21600), '06:00'), (datetime.timedelta(0, 23400), '06:30'), (datetime.timedelta(0, 25200), '07:00'), (datetime.timedelta(0, 27000), '07:30')], null=True),
        ),
        migrations.AlterField(
            model_name='serviceworkorder',
            name='time',
            field=models.TimeField(choices=[(datetime.time(6, 0), '06:00'), (datetime.time(6, 30), '06:30'), (datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00')]),
        ),
    ]
