# Generated by Django 2.1.4 on 2019-02-03 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_data', '0006_auto_20190201_1959'),
        ('services', '0010_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceworkorder',
            name='comments',
        ),
        migrations.AddField(
            model_name='serviceprocedure',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceworkorder',
            name='notes',
            field=models.ManyToManyField(to='common_data.Note'),
        ),
    ]
