# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20180825_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequisition',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_by', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='equipmentrequisition',
            name='released_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='released_by', to='employees.Employee'),
        ),
    ]
