# Generated by Django 2.1.4 on 2019-02-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20190203_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceworkorder',
            name='progress',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
