# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20180826_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequisitionline',
            name='quantity_returned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='equipmentrequisitionline',
            name='returned_condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'), ('broken', 'Not Functioning')], max_length=16, null=True),
        ),
    ]
