# Generated by Django 2.1.4 on 2019-02-04 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_serviceworkorder_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceworkorder',
            name='actual_duration',
        ),
        migrations.AddField(
            model_name='timelog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
