# Generated by Django 2.1.1 on 2018-09-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20180826_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablesrequisition',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=None, related_name='consumable_authorized_by', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='consumablesrequisition',
            name='released_by',
            field=models.ForeignKey(null=True, on_delete=None, related_name='consumable_released_by', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='consumablesrequisition',
            name='requested_by',
            field=models.ForeignKey(on_delete=None, related_name='consumable_requested_by', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='consumablesrequisitionline',
            name='consumable',
            field=models.ForeignKey(on_delete=None, to='inventory.Consumable'),
        ),
        migrations.AlterField(
            model_name='consumablesrequisitionline',
            name='unit',
            field=models.ForeignKey(on_delete=None, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='equipmentrequisitionline',
            name='equipment',
            field=models.ForeignKey(on_delete=None, to='inventory.Equipment'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=None, to='services.ServiceCategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_listed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='serviceperson',
            name='employee',
            field=models.ForeignKey(on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='serviceprocedure',
            name='as_checklist',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='serviceteam',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='service_team_manager', to='services.ServicePerson'),
        ),
        migrations.AlterField(
            model_name='serviceworkorder',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='services.ServiceTeam'),
        ),
    ]
