# Generated by Django 2.1.4 on 2019-02-05 11:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20190204_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='normal_time_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='timelog',
            name='overtime_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
    ]
