# Generated by Django 2.1.1 on 2018-10-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20181008_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceworkorder',
            name='authorized_by',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(user__isnull=False), null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
