# Generated by Django 2.1.4 on 2019-02-06 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20190205_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderrequest',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
        migrations.AlterField(
            model_name='workorderrequest',
            name='service_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.ServiceInvoice'),
        ),
    ]
