# Generated by Django 2.1.4 on 2019-03-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20190206_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablesrequisitionline',
            name='consumable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='equipmentrequisitionline',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='serviceprocedure',
            name='required_consumables',
            field=models.ManyToManyField(blank=True, related_name='consumables', to='inventory.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='serviceprocedure',
            name='required_equipment',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='inventory.InventoryItem'),
        ),
    ]
