# Generated by Django 2.1.4 on 2019-03-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20190324_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderrequest',
            name='combined_invoice',
        ),
        migrations.RemoveField(
            model_name='workorderrequest',
            name='invoice_type',
        ),
        migrations.RemoveField(
            model_name='workorderrequest',
            name='service_invoice',
        ),
    ]
