# Generated by Django 2.1.4 on 2019-03-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0027_auto_20190330_1234'),
        ('services', '0017_auto_20190326_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderrequest',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.Invoice'),
        ),
    ]
