# Generated by Django 2.1.4 on 2019-03-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_workorderrequest_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderrequest',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
    ]
