# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-21 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='individual',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_data.Individual'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_data.Organization'),
        ),
    ]
