# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180721_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
    ]
