# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-11 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180711_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='direct_price',
        ),
        migrations.AddField(
            model_name='item',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='item',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
