# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180808_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedUnitStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveSmallIntegerField()),
                ('operation', models.PositiveSmallIntegerField(choices=[(0, 'sum'), (1, 'difference'), (2, 'product'), (3, 'ratio')])),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='is_derived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='derivedunitstage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.UnitOfMeasure'),
        ),
    ]
