# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-23 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180723_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(),
        ),
    ]
