# Generated by Django 2.2 on 2019-04-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190424_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycheck',
            name='adjusted_by',
            field=models.ForeignKey(limit_choices_to=models.Q(user__isnull=False), null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryController'),
        ),
    ]
