# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180623_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='received',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='fully_received',
            field=models.BooleanField(default=False),
        ),
    ]
