# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryscrappingrecord_inventoryscrappingrecordline_storagemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryscrappingrecord',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
