# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180712_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.WareHouse'),
        ),
    ]
