# Generated by Django 2.2 on 2019-04-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190425_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysettings',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=models.FileField(blank=True, null=True),
        ),
    ]
