# Generated by Django 2.1.1 on 2018-11-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20181115_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='issue_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deferred_date',
            new_name='due',
        ),
        migrations.RenameField(
            model_name='transferorder',
            old_name='issue_date',
            new_name='date',
        ),
    ]
