# Generated by Django 2.1 on 2018-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20181121_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\laska\\Desktop\\caleb\\latrom_software\\App\\latrom\\media'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\laska\\Desktop\\caleb\\latrom_software\\App\\latrom\\media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\laska\\Desktop\\caleb\\latrom_software\\App\\latrom\\media'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\laska\\Desktop\\caleb\\latrom_software\\App\\latrom\\media'),
        ),
    ]
