# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasure',
            old_name='descripition',
            new_name='description',
        ),
    ]
