# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180813_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryscrappingrecordline',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
