# Generated by Django 2.1.8 on 2019-04-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190426_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=models.FileField(blank=True, null=True),
        ),
    ]
