# Generated by Django 2.1.1 on 2018-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20181121_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysettings',
            name='use_consumables_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventorysettings',
            name='use_equipment_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventorysettings',
            name='use_product_inventory',
            field=models.BooleanField(default=True),
        ),
    ]
