# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180627_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_of_order',
            field=models.IntegerField(choices=[(0, 'Cash Order'), (1, 'Deffered Payment Order'), (2, 'Pay on Receipt')], default=1),
        ),
    ]
