# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_paygrade_payroll_taxes'),
        ('inventory', '0007_order_supplier_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('next_adjustment_date', models.DateField(null=True)),
                ('comments', models.TextField()),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.WareHouse')),
            ],
        ),
    ]
