# Generated by Django 2.1.1 on 2018-12-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20181127_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='raw_material',
            field=models.ForeignKey(null=True, on_delete=None, to='inventory.RawMaterial'),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='raw_material',
            field=models.ForeignKey(null=True, on_delete=None, to='inventory.RawMaterial'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Product'), (2, 'Consumable'), (3, 'Equipment'), (4, 'Raw Material')], default=1),
        ),
    ]
