# Generated by Django 2.1.1 on 2018-12-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20181207_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysettings',
            name='use_raw_materials_inventory',
            field=models.BooleanField(default=True),
        ),
    ]
