# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorycheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.FloatField()),
                ('note', models.TextField()),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryCheck')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.WareHouseItem')),
            ],
        ),
    ]
