# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180628_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_of_order',
            field=models.IntegerField(choices=[(0, 'Cash Order'), (1, 'Deffered Payment Order'), (2, 'Pay on Receipt')], default=0),
        ),
    ]
