# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180814_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorysettings',
            old_name='item_sales_pricing_method',
            new_name='product_sales_pricing_method',
        ),
    ]
