# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
