# Generated by Django 2.1 on 2018-12-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorysettings_use_raw_materials_inventory'),
        ('inventory', '0007_auto_20181124_1622'),
    ]

    operations = [
    ]
