# Generated by Django 2.1.8 on 2019-06-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20190521_0505'),
        ('inventory', '0010_order_validated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entries',
            field=models.ManyToManyField(related_name='order_entries', to='accounting.JournalEntry'),
        ),
    ]
