# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180814_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
