# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-02 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180630_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_sales_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
