# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_paygrade_payroll_taxes'),
        ('inventory', '0011_transferorder_transferorderline'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='order_issuing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='receive_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='receiving_inventory_controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
