# Generated by Django 2.1.8 on 2019-06-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_order_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReceiptLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.OrderItem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockReceipt')),
            ],
        ),
    ]
