# Generated by Django 2.1.8 on 2019-06-26 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_creditnote_entry'),
        ('inventory', '0012_stockreceiptline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('debit_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.DebitNoteLine')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Invoice'), (1, 'Transfer'), (2, 'Debit Note')])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Request'), (1, 'In Progress'), (2, 'Completed')])),
                ('debit_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.DebitNote')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.Invoice')),
                ('transfer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.TransferOrder')),
            ],
        ),
        migrations.CreateModel(
            name='StockDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('dispatch_complete', models.BooleanField(default=False)),
                ('dispatched_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryController')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.DispatchRequest')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='received',
        ),
        migrations.RemoveField(
            model_name='stockreceiptline',
            name='line',
        ),
        migrations.RemoveField(
            model_name='transferorderline',
            name='moved_quantity',
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='credit_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.CreditNote'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.TransferOrder'),
        ),
        migrations.AddField(
            model_name='stockreceiptline',
            name='credit_note_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.CreditNoteLine'),
        ),
        migrations.AddField(
            model_name='stockreceiptline',
            name='order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.OrderItem'),
        ),
        migrations.AddField(
            model_name='stockreceiptline',
            name='transfer_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.TransferOrderLine'),
        ),
        migrations.AddField(
            model_name='dispatchline',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockDispatch'),
        ),
        migrations.AddField(
            model_name='dispatchline',
            name='invoice_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.InvoiceLine'),
        ),
        migrations.AddField(
            model_name='dispatchline',
            name='transfer_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.TransferOrderLine'),
        ),
    ]
