# Generated by Django 2.1 on 2019-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20190814_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='direct_price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
