# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-03 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20180703_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_to_date',
            field=models.FloatField(default=0.0),
        ),
    ]
