# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20180815_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.StorageMedia'),
        ),
    ]
