# Generated by Django 2.1.8 on 2019-07-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20190626_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferorder',
            name='actual_completion_date',
        ),
        migrations.RemoveField(
            model_name='transferorder',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='transferorder',
            name='receive_notes',
        ),
    ]
