# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-20 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_accountingsettings'),
        ('inventory', '0013_inventorysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Tax'),
        ),
    ]
