# Generated by Django 2.1.1 on 2018-12-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_accountingsettings_currency_exchange_table'),
        ('inventory', '0013_auto_20181217_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='accounting.JournalEntry'),
        ),
    ]
