# Generated by Django 2.1.8 on 2019-07-01 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20190701_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceiptline',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.StorageMedia'),
        ),
    ]
