# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-03 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20180703_0907'),
        ('inventory', '0014_order_received_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
    ]
