# Generated by Django 2.1.1 on 2018-12-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20181217_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorderline',
            name='moved',
            field=models.BooleanField(default=False),
        ),
    ]
