# Generated by Django 2.2.4 on 2019-08-18 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockreceiptline_location'),
        ('inventory', '0013_auto_20190814_0521'),
    ]

    operations = [
    ]
