# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-19 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180812_2158'),
        ('inventory', '0017_auto_20180816_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('length', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'C:\\Users\\nakamura9a\\Documents\\code\\git\\latrom\\media')),
                ('description', models.TextField(blank=True, default='')),
                ('minimum_order_level', models.IntegerField(default=0)),
                ('maximum_stock_level', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier')),
                ('unit', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.UnitOfMeasure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Asset'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'), ('broken', 'Not Functioning')], default='excellent', max_length=16),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='inventorycontroller',
            name='can_authorize_consumables_requisitions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorycontroller',
            name='can_authorize_equipment_requisitions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.UnitOfMeasure'),
        ),
    ]
