# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-20 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20180819_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='unit_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='consumable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Consumable'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Equipment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Product'), (2, 'Consumable'), (3, 'Equipment')], default=1),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='consumable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Consumable'),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Equipment'),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='item_type',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
    ]
