# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20180820_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\nakamura9a\\Documents\\code\\git\\latrom\\media'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\nakamura9a\\Documents\\code\\git\\latrom\\media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\nakamura9a\\Documents\\code\\git\\latrom\\media'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\nakamura9a\\Documents\\code\\git\\latrom\\media'),
        ),
    ]
