# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20180825_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivedunitstage',
            name='unit',
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='eval_string',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='DerivedUnitStage',
        ),
    ]
