# Generated by Django 2.1.4 on 2019-01-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20190126_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysettings',
            name='stock_valuation_period',
        ),
    ]
