# Generated by Django 2.1.1 on 2018-09-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20180826_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='category',
            field=models.ForeignKey(default=1, on_delete=None, to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.Supplier'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, on_delete=None, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='asset_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='accounting.Asset'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=None, to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.Supplier'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, on_delete=None, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='inventorycheck',
            name='adjusted_by',
            field=models.ForeignKey(on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='inventorycheck',
            name='warehouse',
            field=models.ForeignKey(on_delete=None, to='inventory.WareHouse'),
        ),
        migrations.AlterField(
            model_name='inventorycontroller',
            name='employee',
            field=models.ForeignKey(on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='inventoryscrappingrecord',
            name='controller',
            field=models.ForeignKey(on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='inventoryscrappingrecord',
            name='warehouse',
            field=models.ForeignKey(on_delete=None, to='inventory.WareHouse'),
        ),
        migrations.AlterField(
            model_name='inventoryscrappingrecordline',
            name='product',
            field=models.ForeignKey(on_delete=None, to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='inventoryscrappingrecordline',
            name='scrapping_record',
            field=models.ForeignKey(on_delete=None, to='inventory.InventoryScrappingRecord'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_to',
            field=models.ForeignKey(on_delete=None, to='inventory.WareHouse'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.Supplier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=None, to='accounting.Tax'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='consumable',
            field=models.ForeignKey(null=True, on_delete=None, to='inventory.Consumable'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=None, to='inventory.Equipment'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=None, to='inventory.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=None, to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=None, to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.Supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, on_delete=None, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='category',
            field=models.ForeignKey(default=1, on_delete=None, to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.Supplier'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, on_delete=None, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='inventory_check',
            field=models.ForeignKey(on_delete=None, to='inventory.InventoryCheck'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='warehouse_item',
            field=models.ForeignKey(on_delete=None, to='inventory.WareHouseItem'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='order',
            field=models.ForeignKey(on_delete=None, to='inventory.Order'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='received_by',
            field=models.ForeignKey(default=1, on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='storagemedia',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.StorageMedia'),
        ),
        migrations.AlterField(
            model_name='storagemedia',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='storagemedia',
            name='warehouse',
            field=models.ForeignKey(on_delete=None, to='inventory.WareHouse'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='accounting.Account'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='individual',
            field=models.OneToOneField(null=True, on_delete=None, to='common_data.Individual'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=None, to='common_data.Organization'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='issuing_inventory_controller',
            field=models.ForeignKey(null=True, on_delete=None, related_name='issuing_inventory_controller', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='receiving_inventory_controller',
            field=models.ForeignKey(null=True, on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='receiving_warehouse',
            field=models.ForeignKey(on_delete=None, to='inventory.WareHouse'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='source_warehouse',
            field=models.ForeignKey(on_delete=None, related_name='source_warehouse', to='inventory.WareHouse'),
        ),
        migrations.AlterField(
            model_name='transferorderline',
            name='product',
            field=models.ForeignKey(on_delete=None, to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='transferorderline',
            name='transfer_order',
            field=models.ForeignKey(on_delete=None, to='inventory.TransferOrder'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='inventory_controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='consumable',
            field=models.ForeignKey(null=True, on_delete=None, to='inventory.Consumable'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=None, to='inventory.Equipment'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.StorageMedia'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=None, to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=None, to='inventory.WareHouse'),
        ),
    ]
