# Generated by Django 2.1.4 on 2019-01-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_inventorysettings_stock_valuation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returned_quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
