# Generated by Django 2.1.4 on 2019-01-29 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_auto_20190129_1933'),
        ('inventory', '0022_orderitem_returned_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost_entries',
            field=models.ManyToManyField(related_name='shipping_cost_entries', to='accounting.JournalEntry'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_entry', to='accounting.JournalEntry'),
        ),
    ]
