# Generated by Django 2.1.1 on 2018-09-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180917_1336'),
        ('inventory', '0022_auto_20180917_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='accounting.JournalEntry'),
        ),
    ]
