# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20180707_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit_sales_price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='pricing_method',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'Margin'), (2, 'Markup')], default=0),
        ),
    ]
