# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20180708_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'C:\\Users\\nakamura9a\\Documents\\code\\git\\latrom\\latrom\\media'),
        ),
    ]
