# Generated by Django 2.1.1 on 2018-09-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_order_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysettings',
            name='stock_valuation_period',
            field=models.IntegerField(choices=[(30, 'Month'), (90, 'Quarter'), (182, 'Six Months'), (365, 'One Year')], default=365),
        ),
    ]
