# Generated by Django 2.1.4 on 2019-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_debitnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferorderline',
            name='moved',
        ),
        migrations.AddField(
            model_name='transferorderline',
            name='moved_quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
