# Generated by Django 2.1.1 on 2018-09-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_inventorysettings_stock_valuation_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=None, to='common_data.Individual'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=None, to='common_data.Organization'),
        ),
    ]
