# Generated by Django 2.1.1 on 2018-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20180925_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycheck',
            name='next_adjustment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
