# Generated by Django 2.1.1 on 2018-10-08 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0026_auto_20180925_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issuing_inventory_controller',
            field=models.ForeignKey(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
