# Generated by Django 2.1.4 on 2019-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20190304_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycheck',
            name='next_adjustment_date',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='last_inventory_check_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
