# Generated by Django 2.1.1 on 2018-10-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_order_issuing_inventory_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycheck',
            name='adjusted_by',
            field=models.ForeignKey(limit_choices_to=models.Q(user_isnull=False), on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='inventorycontroller',
            name='employee',
            field=models.ForeignKey(limit_choices_to=models.Q(user_isnull=False), on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='inventoryscrappingrecord',
            name='controller',
            field=models.ForeignKey(limit_choices_to=models.Q(user_isnull=False), on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='received_by',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(user_isnull=False), on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='issuing_inventory_controller',
            field=models.ForeignKey(limit_choices_to=models.Q(user_isnull=False), null=True, on_delete=None, related_name='issuing_inventory_controller', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='receiving_inventory_controller',
            field=models.ForeignKey(limit_choices_to=models.Q(user_isnull=False), null=True, on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='inventory_controller',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(user_isnull=False), null=True, on_delete=None, to='employees.Employee'),
        ),
    ]
