# Generated by Django 2.1.4 on 2019-03-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20190323_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryscrappingrecordline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='consumable',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='transferorderline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='consumable',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='raw_material',
        ),
        migrations.AddField(
            model_name='inventoryscrappingrecordline',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
        migrations.AddField(
            model_name='transferorderline',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Product'), (1, 'Equipment'), (2, 'Consumables'), (3, 'Raw Material')]),
        ),
    ]
