# Generated by Django 2.1.4 on 2019-03-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20190324_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
    ]
