# Generated by Django 2.1.4 on 2019-03-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_warehouseitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='equipment_component',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.EquipmentComponent'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_component',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ProductComponent'),
        ),
    ]
