# Generated by Django 2.1.4 on 2019-03-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_remove_accountingsettings_use_default_chart_of_accounts'),
        ('inventory', '0033_auto_20190327_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomponent',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Tax'),
        ),
    ]
