# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180621_1958'),
        ('accounting', '0002_auto_20180621_1958'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.SalesRepresentative'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Tax'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sales_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.SalesRepresentative'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Customer'),
        ),
        migrations.AddField(
            model_name='quote',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.SalesRepresentative'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Tax'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Quote'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Invoice'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Payment'),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Employee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Invoice'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
