# Generated by Django 2.1.1 on 2018-11-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfig',
            name='next_invoice_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salesconfig',
            name='next_quotation_number',
            field=models.IntegerField(default=1),
        ),
    ]
