# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfig',
            name='include_units_in_sales_invoice',
            field=models.BooleanField(default=True),
        ),
    ]
