# Generated by Django 2.1.1 on 2018-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20181117_0903'),
        ('invoicing', '0002_auto_20181115_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractsale',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='accounting.JournalEntry'),
        ),
        migrations.AlterField(
            model_name='abstractsale',
            name='status',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('draft', 'Draft'), ('invoice', 'Invoice'), ('paid', 'Paid In Full'), ('paid-partially', 'Paid Partially'), ('reversed', 'Reversed')], max_length=16),
        ),
    ]
