# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoice_ship_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
