# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_salesconfig_include_units_in_sales_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='can_offer_discounts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='can_reverse_invoices',
            field=models.BooleanField(default=True),
        ),
    ]
