# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-23 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_auto_20180721_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractsale',
            name='date_issued',
        ),
        migrations.AlterField(
            model_name='abstractsale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
