# Generated by Django 2.1.1 on 2018-11-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_auto_20181121_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesconfig',
            name='apply_price_multiplier',
        ),
        migrations.RemoveField(
            model_name='salesconfig',
            name='price_multiplier',
        ),
    ]
