# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
    ]
