# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180814_0940'),
        ('invoicing', '0003_auto_20180807_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinedinvoiceline',
            name='item',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceline',
            name='item',
        ),
        migrations.AddField(
            model_name='combinedinvoiceline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combinedinvoiceline',
            name='line_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'product'), (2, 'service'), (3, 'expense')]),
        ),
    ]
