# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_bookkeeper'),
        ('invoicing', '0003_invoice_date_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_invoice_comments', models.TextField()),
                ('default_quotation_comments', models.TextField()),
                ('default_credit_note_comments', models.TextField()),
                ('default_terms', models.TextField()),
                ('include_shipping_address', models.BooleanField(default=False)),
                ('business_address', models.TextField()),
                ('logo', models.ImageField(upload_to=b'')),
                ('document_theme', models.IntegerField(choices=[(1, 'Simple'), (2, 'Blue'), (3, 'Steel'), (4, 'Verdant'), (5, 'Warm')])),
                ('currency', models.CharField(choices=[('$', 'Dollars($)'), ('R', 'Rand')], max_length=1)),
                ('apply_price_multiplier', models.BooleanField()),
                ('price_multiplier', models.FloatField(default=0.0)),
                ('business_name', models.CharField(max_length=255)),
                ('payment_details', models.TextField()),
                ('contact_details', models.TextField()),
                ('include_tax_in_invoice', models.BooleanField()),
                ('business_registration_number', models.CharField(max_length=32)),
                ('sales_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Tax')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
