# Generated by Django 2.1.1 on 2018-11-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_auto_20181121_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfig',
            name='currency',
            field=models.ForeignKey(on_delete=None, to='accounting.Currency'),
        ),
    ]
