# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_salesconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfig',
            name='apply_price_multiplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='contact_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='default_credit_note_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='default_invoice_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='default_quotation_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='default_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='include_tax_in_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='logo',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='payment_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='sales_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Tax'),
        ),
    ]
