# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_quoteitem_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='payment',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(default='Payment strictly in 7 days', max_length=64),
        ),
    ]
