# Generated by Django 2.1.8 on 2019-05-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accountingsettings_service_hash'),
        ('invoicing', '0004_auto_20190426_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.JournalEntry'),
        ),
    ]
