# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-23 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20180723_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
