# Generated by Django 2.1.1 on 2018-10-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20180917_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractsale',
            name='invoice_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='abstractsale',
            name='quotation_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
