# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20180719_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
