# Generated by Django 2.1.1 on 2018-11-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20181123_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfig',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='accounting.Currency'),
        ),
    ]
