# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20180622_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='invoice',
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('debit card', 'Debit Card'), ('ecocash', 'EcoCash')], default='transfer', max_length=32),
        ),
    ]
