# Generated by Django 2.1.8 on 2019-08-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20190702_0857'),
        ('invoicing', '0005_creditnote_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.JournalEntry'),
        ),
    ]
