# Generated by Django 2.1.1 on 2018-11-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_auto_20181123_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfig',
            name='use_bill_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesconfig',
            name='use_combined_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesconfig',
            name='use_sales_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesconfig',
            name='use_service_invoice',
            field=models.BooleanField(default=True),
        ),
    ]
