# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_auto_20180723_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
