# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_auto_20180719_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfig',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
    ]
