# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_remove_payment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
    ]
