# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_bill_customer_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billline',
            name='date',
        ),
        migrations.RemoveField(
            model_name='billline',
            name='description',
        ),
    ]
