# Generated by Django 2.1.1 on 2018-12-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_auto_20181127_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
