# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_auto_20180627_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepresentative',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Employee'),
        ),
    ]
