# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-25 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_auto_20180724_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedinvoiceline',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
        migrations.AlterField(
            model_name='serviceinvoiceline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
