# Generated by Django 2.1.4 on 2019-01-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_payment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractsale',
            name='customer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.Customer'),
        ),
        migrations.AlterField(
            model_name='abstractsale',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.JournalEntry'),
        ),
        migrations.AlterField(
            model_name='abstractsale',
            name='salesperson',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.SalesRepresentative'),
        ),
        migrations.AlterField(
            model_name='abstractsale',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Tax'),
        ),
        migrations.AlterField(
            model_name='billline',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.Bill'),
        ),
        migrations.AlterField(
            model_name='billline',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Expense'),
        ),
        migrations.AlterField(
            model_name='combinedinvoiceline',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Expense'),
        ),
        migrations.AlterField(
            model_name='combinedinvoiceline',
            name='invoice',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.CombinedInvoice'),
        ),
        migrations.AlterField(
            model_name='combinedinvoiceline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='combinedinvoiceline',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.SalesInvoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sales_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.SalesRepresentative'),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Currency'),
        ),
        migrations.AlterField(
            model_name='salesconfig',
            name='sales_tax',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Tax'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='ship_from',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.WareHouse'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='serviceinvoiceline',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
    ]
