# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_auto_20180725_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedinvoiceline',
            name='quantity_or_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
