# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_auto_20180628_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
