# Generated by Django 2.1.4 on 2019-01-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_auto_20190104_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
