# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-30 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_auto_20180629_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, default='Thank you for your business'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(default='Pay strictly in 7 days', max_length=64),
        ),
    ]
