# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_combinedinvoiceline_quantity_or_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedinvoiceline',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoicing.CombinedInvoice'),
        ),
    ]
