# Generated by Django 2.1.4 on 2019-01-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_auto_20190129_1933'),
        ('invoicing', '0011_auto_20190113_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_expenses',
            field=models.ManyToManyField(to='accounting.Expense'),
        ),
    ]
