# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-02 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_combinedinvoiceline_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='salesperson',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_from',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sales_rep',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='salesperson',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='quote',
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.SalesInvoice'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='QuoteItem',
        ),
    ]
