# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_auto_20180630_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, default='some comments'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(default='some terms', max_length=64),
        ),
    ]
