# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-03 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_auto_20180802_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractsale',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Tax'),
        ),
    ]
