# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_auto_20180701_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.BusinessCustomer'),
        ),
    ]
