# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-03 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_auto_20180803_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_for', models.PositiveSmallIntegerField(choices=[(0, 'Sales'), (1, 'Service'), (2, 'Bill'), (3, 'Combined')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('debit card', 'Debit Card'), ('ecocash', 'EcoCash')], default='transfer', max_length=32)),
                ('reference_number', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField(default='Thank you for your business')),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Bill')),
                ('combined_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.CombinedInvoice')),
                ('sales_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.SalesInvoice')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.SalesRepresentative')),
                ('service_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.ServiceInvoice')),
            ],
        ),
    ]
