# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_auto_20180702_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
