# Generated by Django 2.1.4 on 2019-03-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20190323_1210'),
        ('invoicing', '0015_auto_20190323_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlinecomponent',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
    ]
