# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_customer_business'),
        ('invoicing', '0016_auto_20180702_1532'),
    ]

    operations = [
    ]
