# Generated by Django 2.1.4 on 2019-03-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0016_productlinecomponent_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedinvoiceline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
    ]
