# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0017_merge_20180702_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.BusinessCustomer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, default='Payment is strictly in seven days '),
        ),
    ]
