# Generated by Django 2.1.4 on 2019-03-26 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_auto_20190326_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='expense',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.ExpenseLineComponent'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.ProductLineComponent'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.ServiceLineComponent'),
        ),
    ]
