# Generated by Django 2.1.4 on 2019-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_auto_20190326_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='price',
        ),
        migrations.AddField(
            model_name='expenselinecomponent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='productlinecomponent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='servicelinecomponent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
