# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-03 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0022_auto_20180703_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, default='some comments'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(default='some terms', max_length=64),
        ),
    ]
