# Generated by Django 2.1.4 on 2019-03-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0022_auto_20190326_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='combined_invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_for',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sales_invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service_invoice',
        ),
        
    ]
