# Generated by Django 2.1.4 on 2019-03-27 10:58

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0023_auto_20190327_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey("invoicing.Invoice", 
                    on_delete=models.SET_NULL, 
                    null=True),
        )
    ]
