# Generated by Django 2.1.4 on 2019-03-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0024_auto_20190327_1258'),
    ]

    operations = [
        
        migrations.DeleteModel(
            name='AbstractSale',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillLine',
        ),
        migrations.DeleteModel(
            name='CombinedInvoice',
        ),
        migrations.DeleteModel(
            name='CombinedInvoiceLine',
        ),
        migrations.DeleteModel(
            name='SalesInvoice',
        ),
        migrations.DeleteModel(
            name='SalesInvoiceLine',
        ),
        migrations.DeleteModel(
            name='ServiceInvoice',
        ),
        migrations.DeleteModel(
            name='ServiceInvoiceLine',
        ),
    ]
