# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-04 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0024_auto_20180703_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='comments',
            field=models.TextField(default='Thank you for your business'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, default='Caleb Kandoro\r\nFBC Bank\r\nAcc No:  5680188141511'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
