# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-05 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0026_auto_20180704_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='account',
        ),
    ]
