# Generated by Django 2.1.4 on 2019-03-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_remove_accountingsettings_use_default_chart_of_accounts'),
        ('invoicing', '0026_auto_20190329_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlinecomponent',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='servicelinecomponent',
            old_name='price',
            new_name='flat_fee',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Tax'),
        ),
        migrations.AddField(
            model_name='servicelinecomponent',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
