# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import invoicing.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0028_auto_20180706_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, default=invoicing.models.get_default_comments),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(default=invoicing.models.get_default_terms, max_length=128),
        ),
    ]
