# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-07 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import invoicing.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0031_auto_20180707_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(blank=True, default=invoicing.models.get_default_terms, max_length=128, null=True),
        ),
    ]
