# Generated by Django 2.1.1 on 2018-10-31 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('created_timestamp', models.DateTimeField(auto_now=True)),
                ('opened_timestamp', models.DateTimeField(blank=True, null=True)),
                ('copy', models.ManyToManyField(blank=True, related_name='copy', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=None, related_name='to', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=None, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(default=False)),
                ('_from', models.ForeignKey(default=1, on_delete=None, related_name='_from', to=settings.AUTH_USER_MODEL)),
                ('_to', models.ForeignKey(default=1, on_delete=None, related_name='_to', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(to='messaging.Message')),
                ('participants', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(default=1, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inbox',
            name='threads',
            field=models.ManyToManyField(to='messaging.MessageThread'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='user',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
