# Generated by Django 2.1.1 on 2018-10-31 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='blind_carbon_copy',
        ),
        migrations.RemoveField(
            model_name='message',
            name='carbon_copy',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.AddField(
            model_name='inbox',
            name='threads',
            field=models.ManyToManyField(to='messaging.MessageThread'),
        ),
        migrations.AddField(
            model_name='message',
            name='copy',
            field=models.ManyToManyField(blank=True, related_name='copy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='_from',
            field=models.ForeignKey(default=1, on_delete=None, related_name='_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='_to',
            field=models.ForeignKey(default=1, on_delete=None, related_name='_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='messages',
            field=models.ManyToManyField(to='messaging.Message'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
