# Generated by Django 2.1.1 on 2018-11-02 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_notification_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='user',
            field=models.OneToOneField(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
