# Generated by Django 2.1.8 on 2019-05-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20190524_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubble',
            name='created_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
