# Generated by Django 2.1.1 on 2018-10-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20181009_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='opened_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
