# Generated by Django 2.1.8 on 2019-05-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20190524_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(null=True, upload_to='C:\\Users\\nakamura9a\\Documents\\code\\git\\latrom\\media\\chat'),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
