# Generated by Django 2.1.8 on 2019-05-31 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_auto_20190531_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sent_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_sent_from', to='messaging.EmailAddress'),
        ),
    ]
