# Generated by Django 2.1.8 on 2019-06-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_email_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='blind_copy',
            field=models.ManyToManyField(blank=True, related_name='blind_copy_email', to='messaging.EmailAddress'),
        ),
    ]
