# Generated by Django 2.1.8 on 2019-06-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_auto_20190601_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts')], default='inbox', max_length=16),
        ),
    ]
