# Generated by Django 2.1.8 on 2019-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_email_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='sender',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_sync_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pop_imap_host',
            field=models.CharField(default='imap.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pop_port',
            field=models.IntegerField(default=993),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_port',
            field=models.IntegerField(default=465),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_server',
            field=models.CharField(default='smtp.gmail.com', max_length=255),
        ),
    ]
