# Generated by Django 2.1.8 on 2019-06-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_auto_20190604_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
