# Generated by Django 2.1.8 on 2019-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_auto_20190607_1009'),
    ]

    operations = [
    ]
