# Generated by Django 2.1.8 on 2019-06-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0017_auto_20190610_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='server_id',
            field=models.IntegerField(blank=True, default='', max_length=16),
        ),
    ]
