# Generated by Django 2.1.8 on 2019-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0019_auto_20190617_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
