# Generated by Django 2.1.8 on 2019-08-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0021_auto_20190623_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='created_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
