# Generated by Django 2.1 on 2019-09-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0022_auto_20190814_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='pop_imap_host',
            new_name='incoming_host',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='pop_port',
            new_name='incoming_port',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='smtp_port',
            new_name='outgoing_port',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='smtp_server',
            new_name='outgoing_server',
        ),
        migrations.AlterField(
            model_name='email',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.EmailFolder'),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.UserProfile'),
        ),
    ]
