# Generated by Django 2.1 on 2019-09-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0023_auto_20190906_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(null=True, upload_to='chat/'),
        ),
        migrations.AlterField(
            model_name='bubble',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messaging/'),
        ),
        migrations.AlterField(
            model_name='email',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messaging/'),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.FileField(blank=True, null=True, upload_to='messaging/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
