# Generated by Django 2.1.1 on 2018-11-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0007_auto_20181127_1521'),
        ('employees', '0008_leave_recorded'),
        ('accounting', '0008_accountingsettings_currency_exchange_table'),
        ('services', '0002_auto_20181101_1514'),
        ('inventory', '0007_auto_20181127_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterialsLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Raw Material'), (1, 'Process Product')])),
                ('quantity', models.FloatField()),
                ('bill', models.ForeignKey(on_delete=None, to='manufacturing.BillOfMaterials')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Line'), (1, 'Batch')])),
                ('duration', models.DurationField()),
                ('bill_of_materials', models.ForeignKey(blank=True, null=True, on_delete=None, to='manufacturing.BillOfMaterials')),
                ('parent_process', models.ForeignKey(on_delete=None, to='manufacturing.Process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_commissioned', models.DateField()),
                ('asset_data', models.ForeignKey(on_delete=None, to='accounting.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessMachineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Product'), (1, 'By-Product'), (2, 'Co-Product'), (3, 'Waste')])),
                ('finished_goods', models.BooleanField(default=False)),
                ('inventory_product', models.ForeignKey(on_delete=None, to='inventory.Product')),
                ('unit', models.ForeignKey(on_delete=None, to='inventory.UnitOfMeasure')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_time', models.PositiveSmallIntegerField(choices=[(0, 'per second'), (0, 'per minute'), (0, 'per hour')])),
                ('quantity', models.FloatField()),
                ('unit', models.ForeignKey(on_delete=None, to='inventory.UnitOfMeasure')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('due', models.DateField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=None, to='invoicing.Customer')),
                ('process', models.ForeignKey(on_delete=None, to='manufacturing.Process')),
                ('product', models.ForeignKey(on_delete=None, to='inventory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employees', models.ManyToManyField(to='employees.Employee')),
                ('process', models.ForeignKey(on_delete=None, to='manufacturing.Process')),
                ('supervisor', models.ForeignKey(on_delete=None, related_name='supervisor', to='employees.Employee')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=None, to='services.ServiceTeam')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSceduleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('Saturday', models.BooleanField(default=False)),
                ('Sunday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WasteGenerationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('comments', models.TextField()),
                ('product', models.ForeignKey(on_delete=None, to='manufacturing.ProcessProduct')),
                ('recorded_by', models.ForeignKey(on_delete=None, to='employees.Employee')),
                ('unit', models.ForeignKey(on_delete=None, to='inventory.UnitOfMeasure')),
            ],
        ),
        migrations.AddField(
            model_name='shiftsceduleline',
            name='schedule',
            field=models.ForeignKey(on_delete=None, to='manufacturing.ShiftSchedule'),
        ),
        migrations.AddField(
            model_name='shiftsceduleline',
            name='shift',
            field=models.ForeignKey(on_delete=None, to='manufacturing.Shift'),
        ),
        migrations.AddField(
            model_name='processmachine',
            name='machine_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='manufacturing.ProcessMachineGroup'),
        ),
        migrations.AddField(
            model_name='processequipment',
            name='machine',
            field=models.ForeignKey(on_delete=None, to='manufacturing.ProcessMachine'),
        ),
        migrations.AddField(
            model_name='processequipment',
            name='machine_group',
            field=models.ForeignKey(on_delete=None, to='manufacturing.ProcessMachineGroup'),
        ),
        migrations.AddField(
            model_name='process',
            name='process_equipment',
            field=models.ForeignKey(on_delete=None, to='manufacturing.ProcessEquipment'),
        ),
        migrations.AddField(
            model_name='process',
            name='product_list',
            field=models.ForeignKey(on_delete=None, to='manufacturing.ProductList'),
        ),
        migrations.AddField(
            model_name='process',
            name='rate',
            field=models.ForeignKey(on_delete=None, to='manufacturing.ProcessRate'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='product',
            field=models.ForeignKey(on_delete=None, to='manufacturing.ProcessProduct'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='raw_material',
            field=models.ForeignKey(on_delete=None, to='inventory.RawMaterial'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='unit',
            field=models.ForeignKey(on_delete=None, to='inventory.UnitOfMeasure'),
        ),
    ]
