# Generated by Django 2.1.1 on 2018-12-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_manufacturingassociate'),
    ]

    operations = [
        migrations.AddField(
            model_name='processequipment',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processrate',
            name='unit_time',
            field=models.PositiveSmallIntegerField(choices=[(0, 'per second'), (1, 'per minute'), (2, 'per hour')]),
        ),
    ]
