# Generated by Django 2.1.1 on 2018-12-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_auto_20181205_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processequipment',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='manufacturing.ProcessMachine'),
        ),
        migrations.AlterField(
            model_name='processequipment',
            name='machine_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='manufacturing.ProcessMachineGroup'),
        ),
    ]
