# Generated by Django 2.1.1 on 2018-12-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_auto_20181205_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='processproduct',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='manufacturing.Process'),
        ),
    ]
