# Generated by Django 2.1.1 on 2018-12-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_processproduct_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processproduct',
            old_name='process',
            new_name='product_list',
        ),
    ]
