# Generated by Django 2.1.1 on 2018-12-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_auto_20181206_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='parent_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='manufacturing.Process'),
        ),
    ]
