# Generated by Django 2.1.1 on 2018-12-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_auto_20181206_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiftSceduleLine',
            new_name='ShiftScheduleLine',
        ),
    ]
