# Generated by Django 2.1.1 on 2018-12-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_auto_20181206_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftscheduleline',
            old_name='Saturday',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='shiftscheduleline',
            old_name='Sunday',
            new_name='sunday',
        ),
    ]
