# Generated by Django 2.1.1 on 2018-12-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0011_auto_20181206_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=None, to='manufacturing.ProcessMachine')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionScheduleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('order', models.ForeignKey(on_delete=None, to='manufacturing.ProductionOrder')),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='process',
        ),
        migrations.AddField(
            model_name='shift',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=None, to='manufacturing.ProcessMachine'),
        ),
    ]
