# Generated by Django 2.1.1 on 2018-12-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0013_auto_20181207_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='manufacturing.ProcessEquipment'),
        ),
        migrations.AlterField(
            model_name='process',
            name='product_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='manufacturing.ProductList'),
        ),
    ]
