# Generated by Django 2.1.4 on 2019-01-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0015_auto_20181211_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterialsline',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.BillOfMaterials'),
        ),
        migrations.AlterField(
            model_name='billofmaterialsline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProcessProduct'),
        ),
        migrations.AlterField(
            model_name='billofmaterialsline',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.RawMaterial'),
        ),
        migrations.AlterField(
            model_name='billofmaterialsline',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='manufacturingassociate',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='process',
            name='bill_of_materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.BillOfMaterials'),
        ),
        migrations.AlterField(
            model_name='process',
            name='parent_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.Process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProcessMachineGroup'),
        ),
        migrations.AlterField(
            model_name='process',
            name='product_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProductList'),
        ),
        migrations.AlterField(
            model_name='process',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProcessRate'),
        ),
        migrations.AlterField(
            model_name='processmachine',
            name='asset_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Asset'),
        ),
        migrations.AlterField(
            model_name='processmachine',
            name='machine_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProcessMachineGroup'),
        ),
        migrations.AlterField(
            model_name='processproduct',
            name='inventory_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='processproduct',
            name='product_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProductList'),
        ),
        migrations.AlterField(
            model_name='processproduct',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='processrate',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.Customer'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.Process'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProcessMachine'),
        ),
        migrations.AlterField(
            model_name='productionscheduleline',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProductionOrder'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='machine',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProcessMachine'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ServiceTeam'),
        ),
        migrations.AlterField(
            model_name='shiftscheduleline',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ShiftSchedule'),
        ),
        migrations.AlterField(
            model_name='shiftscheduleline',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.Shift'),
        ),
        migrations.AlterField(
            model_name='wastegenerationreport',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.ProcessProduct'),
        ),
        migrations.AlterField(
            model_name='wastegenerationreport',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='wastegenerationreport',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasure'),
        ),
    ]
