from django.urls import re_path, path
from invoicing import views

report_urls = [
    re_path(r'^(?P<pk>[\w]+)/customer-statement-form/?$', 
        views.CustomerReportFormView.as_view(),
             name='customer-statement-form'),
    re_path(r'^customer-statement-form/?$', 
        views.CustomerReportFormView.as_view(),
             name='customer-statement-form'),
    re_path(r'^customer-statement/?$', views.CustomerStatement.as_view(),
             name='customer-statement'),
    re_path(r'^customer-statement-pdf/(?P<start>[\w %]+)/(?P<end>[\w %]+)'
        '/(?P<customer>[\d]+)/?$', 
        views.CustomerStatementPDFView.as_view(),
             name='customer-statement-pdf'),
    re_path(r'^invoice-aging/?$', views.InvoiceAgingReport.as_view(),
             name='invoice-aging'),
    re_path(r'^invoice-aging-pdf/?$', views.InvoiceAgingPDFView.as_view(),
             name='invoice-aging-pdf'),
    re_path(r'^sales-report-form/?$', views.SalesReportFormView.as_view(),
             name='sales-report-form'),
    re_path(r'^sales-report/?$', views.SalesReportView.as_view(),
             name='sales-report'),
    re_path(r'^sales-report-pdf/(?P<start>[\w %]+)/(?P<end>[\w %]+)/?$', 
        views.SalesReportPDFView.as_view(),
             name='sales-report-pdf'),
    path("accounts-receivable-report/", 
        views.AccountsReceivableDetailReportView.as_view(), 
        name="accounts-receivable-report"),
    path("sales-by-customer-report/", 
        views.SalesByCustomerReportView.as_view(), 
        name="sales-by-customer-report"),
    path("sales-by-customer-pdf/<str:start>/<str:end>/", 
        views.SalesByCustomerReportPDFView.as_view(), 
        name="sales-by-customer-pdf"),
    path("sales-by-customer-form/", 
        views.SalesByCustomerReportFormView.as_view(), 
        name="sales-by-customer-form"),
    path("customer-payments-report/", 
        views.CustomerPaymentsReportView.as_view(), 
        name="customer-payments-report"),
    path("customer-payments-pdf/<str:start>/<str:end>/", 
        views.CustomerPaymentsPDFView.as_view(), 
        name="customer-payments-pdf"),
    path("customer-payments-form/", 
        views.CustomerPaymentsReportFormView.as_view(), 
        name="customer-payments-form"),
    path("average-days-to-pay-report/", 
        views.AverageDaysToPayReportView.as_view(), 
        name="average-days-to-pay-report"),
    path("average-days-to-pay-pdf/", 
        views.AverageDaysToPayPDFView.as_view(), 
        name="average-days-to-pay-pdf"),
    path("accounts-receivable-report-pdf/", 
        views.AccountsReceivableReportPDFView.as_view(), 
        name="accounts-receivable-report-pdf"),
]