# Generated by Django 2.1.1 on 2018-10-31 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('employees', '0001_initial'),
        ('invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=None, to='invoicing.Customer'),
        ),
        migrations.AddField(
            model_name='expense',
            name='debit_account',
            field=models.ForeignKey(on_delete=None, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debit',
            name='account',
            field=models.ForeignKey(on_delete=None, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='debit',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.JournalEntry'),
        ),
        migrations.AddField(
            model_name='credit',
            name='account',
            field=models.ForeignKey(on_delete=None, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='credit',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.JournalEntry'),
        ),
        migrations.AddField(
            model_name='bookkeeper',
            name='employee',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(user__isnull=False), on_delete=None, to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='debit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='adjustmet',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.JournalEntry'),
        ),
        migrations.AddField(
            model_name='adjustmet',
            name='workbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.WorkBook'),
        ),
    ]
