# Generated by Django 2.1.1 on 2018-10-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
        ('employees', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=None, to='invoicing.Customer'),
        ),
        migrations.AddField(
            model_name='expense',
            name='debit_account',
            field=models.ForeignKey(on_delete=None, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='debit',
            name='account',
            field=models.ForeignKey(on_delete=None, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='debit',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.JournalEntry'),
        ),
        migrations.AddField(
            model_name='credit',
            name='account',
            field=models.ForeignKey(on_delete=None, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='credit',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.JournalEntry'),
        ),
        migrations.AddField(
            model_name='bookkeeper',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='debit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='adjustmet',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.JournalEntry'),
        ),
        migrations.AddField(
            model_name='adjustmet',
            name='workbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.WorkBook'),
        ),
    ]
