# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmet',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Transaction'),
        ),
        migrations.AddField(
            model_name='adjustmet',
            name='workbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.WorkBook'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pay_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.PayGrade'),
        ),
        migrations.AddField(
            model_name='paygrade',
            name='allowances',
            field=models.ManyToManyField(blank=True, to='accounting.Allowance'),
        ),
        migrations.AddField(
            model_name='paygrade',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.CommissionRule'),
        ),
        migrations.AddField(
            model_name='paygrade',
            name='deductions',
            field=models.ManyToManyField(blank=True, to='accounting.Deductions'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Employee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Journal'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
    ]
