# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180721_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='bill',
        ),
    ]
