# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180621_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Journal'),
        ),
    ]
