# Generated by Django 2.1.1 on 2018-10-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20181026_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeeper',
            name='can_create_journals',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bookkeeper',
            name='can_create_orders_and_invoices',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bookkeeper',
            name='can_record_assets',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bookkeeper',
            name='can_record_expenses',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
