# Generated by Django 2.1.1 on 2018-11-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20181031_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeper',
            name='employee',
            field=models.OneToOneField(default=1, limit_choices_to=models.Q(user__isnull=False), on_delete=None, to='employees.Employee'),
        ),
    ]
