# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180710_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='account',
            new_name='debit_account',
        ),
    ]
