# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180710_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='account',
            new_name='debit_account',
        ),
        migrations.AlterField(
            model_name='expense',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Customer'),
        ),
    ]
