# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180622_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deductions',
            new_name='Deduction',
        ),
    ]
