# Generated by Django 2.1.1 on 2018-10-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20181027_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeper',
            name='can_create_journals',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bookkeeper',
            name='can_create_orders_and_invoices',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bookkeeper',
            name='can_record_assets',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bookkeeper',
            name='can_record_expenses',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
