# Generated by Django 2.1.8 on 2019-04-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20190427_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_configured',
        ),
        migrations.RemoveField(
            model_name='interestbearingaccount',
            name='is_configured',
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
    ]
