# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180710_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_sheet_category',
            field=models.CharField(choices=[('current-assets', 'Current Assets'), ('long-term-assets', 'Long Term Assets'), ('current-liabilites', 'Current Liabilites'), ('long-term-liabilites', 'Long Term Liabilites'), ('expense', 'Expense'), ('current-assets', 'Current Assets'), ('not-included', 'Not Included')], default='current-assets', max_length=16),
        ),
    ]
