# Generated by Django 2.1.1 on 2018-11-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20181102_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
