# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180623_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_days',
            field=models.FloatField(default=0),
        ),
    ]
