# Generated by Django 2.1.1 on 2018-10-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20181027_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeeper',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
