# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-16 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20180715_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='debit_account',
            new_name='credit_account',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='debit_account',
        ),
    ]
