# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-30 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_employee_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
