# Generated by Django 2.1.1 on 2018-11-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20181102_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyConversionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyConversionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='currencyconversionline',
            name='conversion_table',
            field=models.ForeignKey(on_delete=None, to='accounting.CurrencyConversionTable'),
        ),
        migrations.AddField(
            model_name='currencyconversionline',
            name='exchange_currency',
            field=models.ForeignKey(on_delete=None, related_name='exchange_currency', to='accounting.Currency'),
        ),
        migrations.AddField(
            model_name='currencyconversionline',
            name='reference_currency',
            field=models.ForeignKey(on_delete=None, related_name='reference_currency', to='accounting.Currency'),
        ),
    ]
