# Generated by Django 2.1.1 on 2018-10-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20181008_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeper',
            name='employee',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(user_isnull=False), on_delete=None, to='employees.Employee'),
        ),
    ]
