# Generated by Django 2.1.1 on 2018-10-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20181008_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeper',
            name='employee',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(user__isnull=False), on_delete=None, to='employees.Employee'),
        ),
    ]
