# Generated by Django 2.1.1 on 2018-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20181113_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyconversionline',
            old_name='exchange_currency',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='currencyconversionline',
            name='reference_currency',
        ),
        migrations.AddField(
            model_name='currencyconversiontable',
            name='reference_currency',
            field=models.ForeignKey(default=1, on_delete=None, related_name='reference_currency', to='accounting.Currency'),
        ),
    ]
