# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-02 09:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20180630_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=128)),
                ('date', models.DateField(default=datetime.date.today)),
                ('memo', models.TextField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Journal')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Journal',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='adjustmet',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='debit',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.JournalEntry'),
        ),
        migrations.AddField(
            model_name='credit',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.JournalEntry'),
        ),
        migrations.AddField(
            model_name='adjustmet',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.JournalEntry'),
        ),
    ]
