# Generated by Django 2.1.8 on 2019-07-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20190521_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Advertising'), (1, 'Bank Service Charges'), (2, 'Dues and Subscriptions'), (3, 'Equipment Rental'), (4, 'Telephone'), (5, 'Vehicles'), (6, 'Travel and Expenses'), (7, 'Supplies'), (8, 'Salaries and Wages'), (9, 'Rent'), (10, 'Payroll Taxes'), (11, 'Legal and Accounting'), (12, 'Insurance'), (13, 'Office Expenses'), (14, 'Carriage Outwards'), (15, 'Other')]),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Advertising'), (1, 'Bank Service Charges'), (2, 'Dues and Subscriptions'), (3, 'Equipment Rental'), (4, 'Telephone'), (5, 'Vehicles'), (6, 'Travel and Expenses'), (7, 'Supplies'), (8, 'Salaries and Wages'), (9, 'Rent'), (10, 'Payroll Taxes'), (11, 'Legal and Accounting'), (12, 'Insurance'), (13, 'Office Expenses'), (14, 'Carriage Outwards'), (15, 'Other')]),
        ),
    ]
