# Generated by Django 2.1.1 on 2018-11-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20181117_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='currency_exchange_table',
            field=models.ForeignKey(default=1, on_delete=None, to='accounting.CurrencyConversionTable'),
        ),
    ]
