# Generated by Django 2.2.4 on 2019-08-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20190702_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='active_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Currency'),
        ),
    ]
