# Generated by Django 2.2.4 on 2019-08-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_accountingsettings_active_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingsettings',
            name='currency_exchange_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.CurrencyConversionTable'),
        ),
    ]
