# Generated by Django 2.1.1 on 2018-12-20 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_accountingsettings_currency_exchange_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmet',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=None, to='accounting.Bookkeeper'),
        ),
        migrations.AddField(
            model_name='adjustmet',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
