# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_expense_last_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestBearingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('cost-of-sales', 'Cost of Sales')], max_length=32)),
                ('description', models.TextField()),
                ('balance_sheet_category', models.CharField(choices=[('current-assets', 'Current Assets'), ('long-term-assets', 'Long Term Assets'), ('current-liabilites', 'Current Liabilites'), ('long-term-liabilites', 'Long Term Liabilites'), ('expense', 'Expense'), ('current-assets', 'Current Assets'), ('not-included', 'Not Included')], default='current-assets', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('interest_interval', models.IntegerField(choices=[(0, 'monthly'), (1, 'annually')], default=1)),
                ('interest_method', models.IntegerField(choices=[(0, 'Simple'), (1, 'Commpound')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.IntegerField(choices=[(0, 'Advertising'), (1, 'Bank Service Charges'), (2, 'Equipment Rental'), (3, 'Dues and Subscriptions'), (4, 'Telephone'), (5, 'Vehicles'), (6, 'Travel and Expenses'), (7, 'Suppliers'), (8, 'Rent'), (9, 'Payroll Expenses'), (10, 'Insurance'), (11, 'Office Expenses'), (12, 'Postage'), (13, 'Other')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cycle', models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (14, 'Bi- Monthly'), (30, 'Monthly'), (90, 'Quarterly'), (182, 'Bi-Annually'), (365, 'Annually')], null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('last_created_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='interest_interval',
        ),
        migrations.RemoveField(
            model_name='account',
            name='interest_method',
        ),
        migrations.RemoveField(
            model_name='account',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='last_created_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recurring',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='start_date',
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='debit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
    ]
