# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20180702_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_sheet_category',
            field=models.CharField(choices=[('current-assets', 'Current Assets'), ('long-term-assets', 'Long Term Assets'), ('current-liabilites', 'Current Liabilites'), ('expense', 'Expense'), ('current-assets', 'Current Assets'), ('not-included', 'Not Included')], default='current-assets', max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cost-of-sales', 'Cost of Sales')], max_length=32),
        ),
    ]
