# Generated by Django 2.1.1 on 2018-12-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20181220_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmet',
            name='adjusting_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjusting_entry', to='accounting.JournalEntry'),
        ),
        migrations.AlterField(
            model_name='adjustmet',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='accounting.JournalEntry'),
        ),
    ]
