# Generated by Django 2.1 on 2019-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20190820_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='equipment_capitalization_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
