# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-03 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20180702_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='journal',
            name='end_period',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='start_period',
            field=models.DateField(null=True),
        ),
    ]
