# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_bookkeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_financial_year', models.DateField()),
                ('use_default_chart_of_accounts', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
