# Generated by Django 2.1.1 on 2018-12-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20181220_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adjustmet',
            new_name='Adjustment',
        ),
    ]
