# Generated by Django 2.1.1 on 2018-12-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20181220_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='accounting.JournalEntry'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='accounting.JournalEntry'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Advertising'), (1, 'Bank Service Charges'), (2, 'Equipment Rental'), (3, 'Dues and Subscriptions'), (4, 'Telephone'), (5, 'Vehicles'), (6, 'Travel and Expenses'), (7, 'Rent'), (8, 'Payroll Taxes'), (9, 'Insurance'), (10, 'Office Expenses'), (11, 'Postage'), (12, 'Other')]),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Advertising'), (1, 'Bank Service Charges'), (2, 'Equipment Rental'), (3, 'Dues and Subscriptions'), (4, 'Telephone'), (5, 'Vehicles'), (6, 'Travel and Expenses'), (7, 'Rent'), (8, 'Payroll Taxes'), (9, 'Insurance'), (10, 'Office Expenses'), (11, 'Postage'), (12, 'Other')]),
        ),
    ]
