# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20180703_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='end_period',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='start_period',
        ),
        migrations.AddField(
            model_name='deduction',
            name='trigger',
            field=models.IntegerField(choices=[(0, 'All Income'), (1, 'Taxable Income'), (2, 'Tax')], default=0),
        ),
        migrations.AlterField(
            model_name='adjustmet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
