# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20180705_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
