# Generated by Django 2.1.4 on 2019-01-11 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20190104_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='control_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='interestbearingaccount',
            name='bank_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interestbearingaccount',
            name='control_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interestbearingaccount',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Account'),
        ),
    ]
