# Generated by Django 2.1.4 on 2019-01-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20190112_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
