# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_asset_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.IntegerField(choices=[(0, 'Land'), (1, 'Buildings'), (2, 'Vehicles'), (3, 'LeaseHold Improvements'), (4, 'Furniture and Fixtures'), (5, 'Equipment')]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.IntegerField(choices=[(0, 'Advertising'), (1, 'Bank Service Charges'), (2, 'Equipment Rental'), (3, 'Dues and Subscriptions'), (4, 'Telephone'), (5, 'Vehicles'), (6, 'Travel and Expenses'), (7, 'Suppliers'), (8, 'Rent'), (9, 'Payroll Expenses'), (10, 'Insurance'), (11, 'Office Expenses'), (12, 'Postage'), (13, 'Other')]),
        ),
    ]
