# Generated by Django 2.1.4 on 2019-01-12 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_journalentry_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='debit_account',
        ),
        migrations.AddField(
            model_name='asset',
            name='credit_account',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.Account'),
        ),
    ]
