# Generated by Django 2.1.4 on 2019-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_auto_20190112_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='interestbearingaccount',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
