# Generated by Django 2.1.4 on 2019-01-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_auto_20190127_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Advertising'), (1, 'Bank Service Charges'), (2, 'Equipment Rental'), (3, 'Dues and Subscriptions'), (4, 'Telephone'), (5, 'Vehicles'), (6, 'Travel and Expenses'), (7, 'Rent'), (8, 'Payroll Taxes'), (9, 'Insurance'), (10, 'Office Expenses'), (11, 'Carriage Outwards'), (12, 'Other')]),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Advertising'), (1, 'Bank Service Charges'), (2, 'Equipment Rental'), (3, 'Dues and Subscriptions'), (4, 'Telephone'), (5, 'Vehicles'), (6, 'Travel and Expenses'), (7, 'Rent'), (8, 'Payroll Taxes'), (9, 'Insurance'), (10, 'Office Expenses'), (11, 'Carriage Outwards'), (12, 'Other')]),
        ),
    ]
