# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_auto_20180709_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
