# Generated by Django 2.1.4 on 2019-02-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_auto_20190129_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='debit_account',
            field=models.ForeignKey(limit_choices_to=models.Q(type='asset'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Account'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='debit_account',
            field=models.ForeignKey(limit_choices_to=models.Q(type='asset'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Account'),
        ),
    ]
