# Generated by Django 2.1.4 on 2019-03-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_auto_20190201_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='use_default_chart_of_accounts',
        ),
    ]
