from .models import (create_test_inventory_models, 
    CommonModelTests, 
    ItemManagementModelTests, 
    ItemModelTests, 
    WarehouseModelTests)
from .views import (ConfigWizardTests, 
    CommonViewTests, 
    InventoryManagementViewTests, 
    ItemViewTests, 
    OrderViewTests, 
    SupplierViewTests, 
    OrderViewTests, 
    WarehouseViewTests, 
    ReportViewTests, 
    TransferViewTests)