# Generated by Django 2.1.1 on 2018-11-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.CharField(blank=True, choices=[('file-chart-line', 'Report'), ('truck', 'Delivery'), ('users', 'Meeting'), ('stopwatch', 'Deadline'), ('book', 'Training'), ('calendar', 'Event')], max_length=32),
        ),
    ]
