# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20180817_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(6, 0), b'06:00'), (datetime.time(6, 30), b'06:30'), (datetime.time(7, 0), b'07:00'), (datetime.time(7, 30), b'07:30'), (datetime.time(8, 0), b'08:00'), (datetime.time(8, 30), b'08:30'), (datetime.time(9, 0), b'09:00'), (datetime.time(9, 30), b'09:30'), (datetime.time(10, 0), b'10:00'), (datetime.time(10, 30), b'10:30'), (datetime.time(11, 0), b'11:00'), (datetime.time(11, 30), b'11:30'), (datetime.time(12, 0), b'12:00'), (datetime.time(12, 30), b'12:30'), (datetime.time(13, 0), b'13:00'), (datetime.time(13, 30), b'13:30'), (datetime.time(14, 0), b'14:00'), (datetime.time(14, 30), b'14:30'), (datetime.time(15, 0), b'15:00'), (datetime.time(15, 30), b'15:30'), (datetime.time(16, 0), b'16:00'), (datetime.time(16, 30), b'16:30'), (datetime.time(17, 0), b'17:00'), (datetime.time(17, 30), b'17:30')], null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low')], default='normal', max_length=8),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(6, 0), b'06:00'), (datetime.time(6, 30), b'06:30'), (datetime.time(7, 0), b'07:00'), (datetime.time(7, 30), b'07:30'), (datetime.time(8, 0), b'08:00'), (datetime.time(8, 30), b'08:30'), (datetime.time(9, 0), b'09:00'), (datetime.time(9, 30), b'09:30'), (datetime.time(10, 0), b'10:00'), (datetime.time(10, 30), b'10:30'), (datetime.time(11, 0), b'11:00'), (datetime.time(11, 30), b'11:30'), (datetime.time(12, 0), b'12:00'), (datetime.time(12, 30), b'12:30'), (datetime.time(13, 0), b'13:00'), (datetime.time(13, 30), b'13:30'), (datetime.time(14, 0), b'14:00'), (datetime.time(14, 30), b'14:30'), (datetime.time(15, 0), b'15:00'), (datetime.time(15, 30), b'15:30'), (datetime.time(16, 0), b'16:00'), (datetime.time(16, 30), b'16:30'), (datetime.time(17, 0), b'17:00'), (datetime.time(17, 30), b'17:30')], null=True),
        ),
    ]
