# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20180818_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder',
            field=models.DurationField(choices=[(datetime.timedelta(0), 'At event start')], default=datetime.timedelta(0)),
        ),
    ]
