# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_event_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reminder',
            field=models.DurationField(choices=[(datetime.timedelta(0), 'At event start'), (datetime.timedelta(0, 900), '15 min before'), (datetime.timedelta(0, 3600), '1 hour before'), (datetime.timedelta(0, 10800), '3 hour before'), (datetime.timedelta(0, 21600), '6 hours before'), (datetime.timedelta(1), '1 Day before'), (datetime.timedelta(3), '3 Days before'), (datetime.timedelta(7), '1 week before'), (datetime.timedelta(14), '2 weeks before'), (datetime.timedelta(30), '1 month before')], default=datetime.timedelta(0)),
        ),
    ]
