# Generated by Django 2.1.4 on 2019-03-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20190126_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannerconfig',
            name='autogenerate_events_from_models',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
