# Generated by Django 2.1.4 on 2019-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20190306_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repeat',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Never'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Annually')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
