# Generated by Django 2.1.1 on 2018-09-17 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20180825_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='invoicing.Customer'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='inventory.Supplier'),
        ),
    ]
